wandb_version: 1

dataset:
  desc: null
  value: dataset
epochs:
  desc: null
  value: 5
configuration:
  desc: null
  value: custom
batch_size:
  desc: null
  value: 16
img_size:
  desc: null
  value: 224
unfreezed_layers:
  desc: null
  value: 9
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712397044.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
